% Compute power spectrum

% Generated by MATLAB(R) 9.3 and Signal Processing Toolbox 7.5.
% Generated on: 23-Mar-2018 18:32:10

% Parameters
timeLimits = seconds([0 2.555]); % seconds
frequencyLimits = [0 100]; % Hz

%%
% Index into signal time region of interest
VarName1_ROI = VarName1(:);
sampleRate = 200; % Hz
startTime = 0; % seconds
timeValues = startTime + (0:length(VarName1_ROI)-1).'/sampleRate;
VarName1_ROI = timetable(seconds(timeValues(:)),VarName1_ROI,'VariableNames',{'Data'});
VarName1_ROI = VarName1_ROI(timerange(timeLimits(1),timeLimits(2)),1);

% Compute spectral estimate
% Run the function call below without output arguments to plot the results
[PVarName1_ROI, FVarName1_ROI] = pspectrum(VarName1_ROI, ...
    'FrequencyLimits',frequencyLimits);
